# FE CI GITHUB ACTIONS WORKFLOW
name: FE CI Workflow

on:
  push:
    branches:
      - main
      - develop
    pull_request:
    workflow_dispatch:

jobs:
  lint:
    name: Lint CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
        name: Install node modules
        run: npm install

      - name: Check Lint
        run: npm run lint
